# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/plantSat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto_files/plantSat.proto\"w\n\rSimpleMessage\x12\x11\n\tunix_time\x18\x01 \x02(\x05\x12\x10\n\x08\x61ir_temp\x18\x02 \x02(\x02\x12\x14\n\x0c\x61ir_pressure\x18\x03 \x02(\x02\x12\x14\n\x0cthermistor_1\x18\x04 \x02(\x02\x12\x15\n\rinternal_temp\x18\x05 \x02(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.plantSat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SIMPLEMESSAGE']._serialized_start=30
  _globals['_SIMPLEMESSAGE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
